# Site settings
title: "Hi, I'm Ethan."
email: ejaffee01@gmail.com
description: "Ethan Jaffee's personel webpage"
baseurl: ""
url: "http://ethanjaffee.com"
title_description: "I study Computer Science and Spanish at the University of Maryland, College Park."
title_image: /image.jpg

# Social usernames/URLs
github_username: ejaffee01
linkedin_link: https://www.linkedin.com/in/ethan-jaffee-4a527a173/
mail: ejaffee01@gmail.com
resume_link: http://ethanjaffee.com/resume.pdf

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
