# Site settings
title: "Ethan Jaffee"
email: ejaffee01@gmail.com
description: "Ethan Jaffee's personel webpage"
baseurl: ""
url: "http://ethanjaffee.com"
title_description: "Ethan Jaffee is a senior at Westfield High School intending to major in Computer or Information Science."
title_image: /image.jpg

# Social usernames/URLs
twitter_username: ejaffee01
github_username: ejaffee01
linkedin_link: https://www.linkedin.com/in/ethan-jaffee-4a527a173/
facebook_link: https://www.facebook.com/profile.php?id=100008785533920
mail: ejaffee01@gmail.com
resume_link: http://ethanjaffee.com/resume.pdf

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
