# Site settings
title: "Ethan Jaffee"
email: ejaffee01@gmail.com
description: "Ethan Jaffee's personel webpage"
baseurl: ""
url: "http://ethanjaffee.com"
title_description: "A dark blog theme for Jekyll focusing on a clear reading experience. Large text and a narrow body makes carte noire a gorgeous read. With excellent code snippet support and integrated tools such as AddThis and Disqus giving your Jekyll blog all the functionality your users expect."
title_image: "https://scontent.fewr1-1.fna.fbcdn.net/v/t1.0-9/16473295_1649472615355574_5785544518198790549_n.jpg?_nc_cat=109&_nc_ht=scontent.fewr1-1.fna&oh=308834036c655f744ec2fa1eda1971e7&oe=5C8AD8CE"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: _jacobtomlinson
github_username:  jacobtomlinson
instagram_username: 
reddit_username: 
linkedin_link: http://carte-noire.jacobtomlinson.co.uk/
google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/
xing_link:
facebook_link:


# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
